[package]
name = "RustLearn"
version = "0.1.0"
authors = ["Vladislav Markushin <vladislav.markushin@bitfury.com>"]
edition = "2018"

[dependencies]
log = "*"
env_logger = "0.7.1"
lazy_static = "1.4.0"
