[package]
name = "interpreter"
version = "0.1.0"
authors = ["Vladislav Markushin <negigic@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
lazy_static = "1.4.0"
err-derive = "0.2.2"

[dev-dependencies]
criterion = "0.3.1"
#gag = "0.1.10"
